version: '3'

services:
  node_x:
    build:
      context: .
      dockerfile: SetupFile
    environment:
      - NODE_NAME=X
      - NODE_LIST=X,Y,Z
      - APP_PORT=6000
    ports:
      - "6000:6000"

  node_y:
    build:
      context: .
      dockerfile: SetupFile
    environment:
      - NODE_NAME=Y
      - NODE_LIST=X,Y,Z
      - APP_PORT=6001
    ports:
      - "6001:6000"

  node_z:
    build:
      context: .
      dockerfile: SetupFile
    environment:
      - NODE_NAME=Z
      - NODE_LIST=X,Y,Z
      - APP_PORT=6002
    ports:
      - "6002:6000"
